[package]
name = "hpt-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
hpt-common = { path = "../hpt-common" }
hpt-types = { path = "../hpt-types" }
anyhow = "1.0.75"
num = "0.4"
rand_distr = "0.4.3"

[features]
track_caller = []
stdsimd = ["hpt-types/stdsimd"]
archsimd = ["hpt-types/archsimd"]