[package]
name = "tensor-cudakernels"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11.1", default-features = false }

[build-dependencies]
phf = { version = "0.11.1", default-features = false }
phf_codegen = "0.11.1"
regex = "1.11.1"
# sha2 = "0.10.8"