[package]
name = "tensor-allocator"
version = "0.1.0"
edition = "2021"

[dependencies]
lru = "0.12.3"
once_cell = "1.19.0"
lazy_static = "1.4.0"
hashbrown = "0.14.3"
wgpu = { version = "22.1.0", features = ["naga-ir"]  }