
[package]
name = "e_tensor"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "tensor-allocator",
    "tensor-common",
    "tensor-dyn",
    "tensor-traits",
    "tensor-types",
    "tensor-macros",
    "tensor-iterator",
    "tensor-display",
    "tensor-bench",
    "tensor-tests",
    "tensor-dataloader",
    "tensor-codegen",
    "tensor-cudakernels",
]

[dependencies]
tensor-dyn = { path = "tensor-dyn", features = ["track_caller", "codegen"] }
tensor-common = { path = "tensor-common" }
anyhow = "1.0.40"
half = "2.4.1"
tch = { version = "0.17.0", features = ["download-libtorch"] }
rayon = "1.8.0"
cache-size = "0.7.0"
rust_xlsxwriter = "=0.25.0"
num-complex = "0.4"
regex = "1.11.1"
num = "0.4"
serde = "1.0.217"
serde_json = "1.0"
safetensors = "0.5.0"
memmap2 = "0.9.0"

[[test]]
name = "tensor-tests"
path = "tensor-tests"

[[bin]]
name = "etensor"
path = "src/main.rs"

[profile.release]
opt-level = 0
incremental = false
debug = false
# lto = "fat"
# codegen-units = 1

[profile.dev]
opt-level = 0
incremental = false
debug = true
# lto = "fat"
# codegen-units = 1

[profile.test]
opt-level = 0
incremental = false
debug = true
# lto = "fat"
# codegen-units = 1
