
[package]
name = "e_tensor"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "tensor-allocator",
    "tensor-common",
    "tensor-dyn",
    "tensor-traits",
    "tensor-types",
    "tensor-macros",
    "tensor-iterator",
    "tensor-display", "tensor-bench",
    "tensor-tests",
]

[dependencies]
tensor-dyn = { path = "tensor-dyn", features = ["track_caller", "simd"]}
tensor-common = { path = "tensor-common"}
anyhow = "1.0.40"
half = "2.4.1"
tch = "0.17.0"

[[bin]]
name = "etensor"
path = "src/main.rs"


[profile.dev]
opt-level = 3
incremental = false
debug = "full"
lto = "fat"
codegen-units = 1

[profile.release]
opt-level = 3
incremental = false
debug = "full"
lto = "fat"
codegen-units = 1
