
[package]
name = "e_tensor"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "tensor-allocator",
    "tensor-common",
    "tensor-dyn",
    "tensor-traits",
    "tensor-types",
    "tensor-macros",
    "tensor-iterator",
    "tensor-display",
]

[dependencies]
tensor-dyn = { path = "tensor-dyn" }
anyhow = "1.0.40"
wgpu = { version = "22.1.0", features = ["naga-ir"] }
rayon = "1.8.0"
half = "2.4.1"
wide = "0.7.28"
cudarc = { version = "0.11.8", features = ["cuda-12010"] }
winapi = { version = "0.3", features = ["psapi", "handleapi", "processthreadsapi"] }

[[bin]]
name = "etensor"
path = "src/main.rs"


[profile.dev]
opt-level = 3
incremental = true
debug = true
lto = "fat"

[profile.release]
opt-level = 3
incremental = true
debug = true
lto = "fat"