[package]
name = "hpt-cudakernels"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
phf = { version = "0.11.1", default-features = false }

[build-dependencies]
phf = { version = "0.11.1", default-features = false }
phf_codegen = "0.11.1"
regex = "1.11.1"

[lib]
path = "src/lib.rs"
required-features = ["cuda"]

[features]
default = []
cuda = []