[package]
name = "tensor-common"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-types = { path = "../tensor-types" }
anyhow = "1.0.75"
getset = "0.1.2"
thiserror = "1.0.63"

[features]
track_caller = []
bound_check = []