[package]
name = "hpt-display"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hpt-traits = { path = "../hpt-traits" }
hpt-common = { path = "../hpt-common" }
hpt-types = { path = "../hpt-types" }
anyhow = "1.0.75"
num-complex = "0.4"