[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "target-cpu=native",
]

[target.'cfg(target_os = "windows")']
rustflags = [
    "-C", "target-feature=-avx2",
    "-C", "target-feature=-fma",
    "-C", "target-feature=-f16c",
] 