[package]
name = "tensor-display"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-traits = { path = "../tensor-traits" }
tensor-common = { path = "../tensor-common" }
tensor-types = { path = "../tensor-types" }
anyhow = "1.0.75"
num-complex = "0.4"