[package]
name = "tensor-dyn"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-types = { path = "../tensor-types" }
tensor-common = { path = "../tensor-common" }
tensor-iterator = { path = "../tensor-iterator" }
tensor-traits = { path = "../tensor-traits" }
tensor-allocator = { path = "../tensor-allocator" }
tensor-macros = { path = "../tensor-macros" }
tensor-display = { path = "../tensor-display" }
rand_distr = "0.4.3"
rand = "0.8.5"
threadpool = "1.8.1"
anyhow = "1.0.75"
rayon = "1.8.0"
num = "0.4.1"
half = { version = "2.3.1", features = ["num-traits", "rand_distr"] }
gemm = { version = "0.18.0", features = ["rayon"] }
