[package]
name = "tensor-dyn"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-types = { path = "../tensor-types" }
tensor-common = { path = "../tensor-common" }
tensor-iterator = { path = "../tensor-iterator" }
tensor-traits = { path = "../tensor-traits" }
tensor-allocator = { path = "../tensor-allocator" }
tensor-macros = { path = "../tensor-macros" }
tensor-display = { path = "../tensor-display" }
rand_distr = "0.4.3"
rustfft = "6.1.0"
cudarc = {version = "0.11.6", features = ["cuda-12010"]}
wgpu = { version = "22.1.0", features = ["naga-ir"]  }
rand = "0.8.5"
threadpool = "1.8.1"
anyhow = "1.0.75"
rayon = "1.8.0"
num = "0.4.1"
bytemuck = "1.16.3"
itertools = "0.13.0"
flume = "0.11.0"
half = { version = "2.3.1", features = ["num-traits", "rand_distr"] }
gemm = { version = "0.18.0", features = ["rayon"] }
hashbrown = "0.14.5"
