[package]
name = "tensor-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-macros = { path = "../tensor-macros" }
tensor-common = { path = "../tensor-common" }
tensor-dyn = { path = "../tensor-dyn", features = [
    "simd",
    "track_caller",
    "bound_check",
] }
tensor-types = { path = "../tensor-types" }
serde_json = "1"
tch = "0.17.0"
anyhow = "1.0.75"
rayon = { version = "1.10.0", default-features = false }

[profile.dev]
opt-level = 3
incremental = false
debug = true

[profile.release]
opt-level = 3
incremental = false
debug = true
