[package]
name = "tensor-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tensor-macros = { path = "../tensor-macros" }
tensor-compiler = { path = "../tensor-compiler" }
tensor-common = { path = "../tensor-common" }
serde_json = "1"