name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true  # Use nightly for the entire workflow
        components: clippy, rustfmt  # Optional: add useful components
    - name: build torch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.4.0%2Bcpu.zip
        unzip libtorch-shared-with-deps-2.4.0+cpu.zip -d ~/libtorch
        export LIBTORCH_HOME=~/libtorch/libtorch
        export LD_LIBRARY_PATH=$LIBTORCH_HOME/lib:$LD_LIBRARY_PATH
        export CMAKE_PREFIX_PATH=$LIBTORCH_HOME:$CMAKE_PREFIX_PATH
        echo "LIBTORCH_HOME: $LIBTORCH_HOME"
        echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
        echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
    - name: Build
      run: |
        cd tensor-tests
        cargo build --verbose
    - name: Run tests
      run: |
        cd tensor-tests
        cargo test --verbose
